import { Language } from './types';

export const LANGUAGES: { label: string; value: Language }[] = [
  { label: 'English', value: 'English' },
  { label: 'Español', value: 'Spanish' },
  { label: 'Français', value: 'French' },
  { label: 'Deutsch', value: 'German' },
  { label: 'Italiano', value: 'Italian' },
  { label: '日本語', value: 'Japanese' },
  { label: '한국어', value: 'Korean' },
  { label: 'Português', value: 'Portuguese' },
  { label: 'Русский', value: 'Russian' },
  { label: 'ไทย', value: 'Thai' },
  { label: 'Tiếng Việt', value: 'Vietnamese' },
  { label: '简体中文', value: 'ChineseSimplified' },
  { label: '繁體中文', value: 'ChineseTraditional' },
  { label: 'Indonesian', value: 'Indonesian' },
  { label: 'Türkçe', value: 'Turkish' },
];

export const UI_TRANSLATIONS: Record<Language, any> = {
  English: {
    search: 'Search...',
    all: 'All',
    characters: 'Characters',
    weapons: 'Weapons',
    artifacts: 'Artifacts',
    materials: 'Materials',
    enemies: 'Enemies',
    food: 'Food',
    reactions: 'Reactions',
    achievements: 'Achievements',
    outfits: 'Outfits',
    domains: 'Domains',
    windgliders: 'Wind Gliders',
    animals: 'Animals',
    tcg: 'TCG Cards',
    namecards: 'Namecards',
    geography: 'Geography',
    adventureranks: 'Adventure Ranks',
    crafts: 'Crafts',
    elements: 'Elements',
    emojis: 'Emojis',
    voiceovers: 'Voiceovers',
    tcgcardbacks: 'TCG Card Backs',
    tcgcardboxes: 'TCG Card Boxes',
    tcgdetailedrules: 'TCG Rules',
    tcgenemycards: 'TCG Enemy Cards',
    tcgkeywords: 'TCG Keywords',
    tcglevelrewards: 'TCG Rewards',
    tcgstatuseffects: 'TCG Status Effects',
    tcgsummons: 'TCG Summons',
    details: 'Details',
    rarity: 'Rarity',
    element: 'Element',
    weapon: 'Weapon',
    birthday: 'Birthday',
    constellation: 'Constellation',
    affiliation: 'Affiliation',
    region: 'Region',
    baseAttack: 'Base Attack',
    substat: 'Substat',
    set1: '1-Piece Set',
    set2: '2-Piece Set',
    set4: '4-Piece Set',
    type: 'Type',
    source: 'Source',
    recipe: 'Recipe',
    reward: 'Reward',
    unlock: 'Unlock',
    exp: 'EXP',
    result: 'Result',
    quality: 'Quality',
    character: 'Character',
    effect: 'Effect',
    description: 'Description',
    noItems: 'No items found',
    itemsCount: 'items',
  },
  Spanish: {
    search: 'Buscar...',
    all: 'Todos',
    characters: 'Personajes',
    weapons: 'Armas',
    artifacts: 'Artefactos',
    materials: 'Materiales',
    enemies: 'Enemigos',
    food: 'Comida',
    reactions: 'Reacciones',
    achievements: 'Logros',
    outfits: 'Vestuarios',
    domains: 'Dominios',
    windgliders: 'Alas',
    animals: 'Animales',
    tcg: 'Cartas TCG',
    namecards: 'Tarjetas',
    geography: 'Geografía',
    adventureranks: 'Rangos de Aventura',
    crafts: 'Artesanía',
    elements: 'Elementos',
    emojis: 'Emojis',
    voiceovers: 'Líneas de voz',
    tcgcardbacks: 'Reversos TCG',
    tcgcardboxes: 'Cajas TCG',
    tcgdetailedrules: 'Reglas TCG',
    tcgenemycards: 'Enemigos TCG',
    tcgkeywords: 'Palabras Clave TCG',
    tcglevelrewards: 'Recompensas TCG',
    tcgstatuseffects: 'Efectos TCG',
    tcgsummons: 'Invocaciones TCG',
    details: 'Detalles',
    rarity: 'Rareza',
    element: 'Elemento',
    weapon: 'Arma',
    birthday: 'Cumpleaños',
    constellation: 'Constelación',
    affiliation: 'Afiliación',
    region: 'Región',
    baseAttack: 'Ataque Base',
    substat: 'Atributo Secundario',
    set1: 'Conjunto de 1 pieza',
    set2: 'Conjunto de 2 piezas',
    set4: 'Conjunto de 4 piezas',
    type: 'Tipo',
    source: 'Fuente',
    recipe: 'Receta',
    reward: 'Recompensa',
    unlock: 'Desbloquear',
    exp: 'EXP',
    result: 'Resultado',
    quality: 'Calidad',
    character: 'Personaje',
    effect: 'Efecto',
    description: 'Descripción',
    noItems: 'No se encontraron elementos',
    itemsCount: 'elementos',
  },
} as any;

// Fill in missing languages to satisfy the type checker
const baseTranslations = UI_TRANSLATIONS.English;
LANGUAGES.forEach(lang => {
  if (!UI_TRANSLATIONS[lang.value]) {
    UI_TRANSLATIONS[lang.value] = baseTranslations;
  }
});
