import { Language } from './types';

export const LANGUAGES: Language[] = [
  'English', 'Spanish', 'French', 'German', 'Italian', 
  'Japanese', 'Korean', 'Portuguese', 'Russian', 'Thai', 
  'Vietnamese', 'ChineseSimplified', 'ChineseTraditional', 
  'Indonesian', 'Turkish'
];

export const UI_TRANSLATIONS: Record<Language, any> = {
  English: {
    home: 'Home',
    characters: 'Characters',
    weapons: 'Weapons',
    artifacts: 'Artifacts',
    materials: 'Materials',
    enemies: 'Enemies',
    food: 'Food',
    reactions: 'Reactions',
    search: 'Search Teyvat...',
    all: 'All',
    noItems: 'No items found',
    loading: 'Loading...',
    back: 'Back',
    details: 'Details',
    stats: 'Stats',
    talents: 'Talents',
    constellations: 'Constellations',
    refinements: 'Refinements',
    setBonus: 'Set Bonus',
    rarity: 'Rarity',
    element: 'Element',
    weaponType: 'Weapon Type',
    region: 'Region',
    affiliation: 'Affiliation',
    birthday: 'Birthday',
  },
  Spanish: {
    home: 'Inicio',
    characters: 'Personajes',
    weapons: 'Armas',
    artifacts: 'Artefactos',
    materials: 'Materiales',
    enemies: 'Enemigos',
    food: 'Comida',
    reactions: 'Reacciones',
    search: 'Buscar en Teyvat...',
    all: 'Todo',
    noItems: 'No se encontraron elementos',
    loading: 'Cargando...',
    back: 'Volver',
    details: 'Detalles',
    stats: 'Estadísticas',
    talents: 'Talentos',
    constellations: 'Constelaciones',
    refinements: 'Refinamientos',
    setBonus: 'Bono de Conjunto',
    rarity: 'Rareza',
    element: 'Elemento',
    weaponType: 'Tipo de Arma',
    region: 'Región',
    affiliation: 'Afiliación',
    birthday: 'Cumpleaños',
  },
  // Add other languages as needed...
} as any;
